language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9-dev

branches:
  except:
    - gh-pages

install:
  - pip install .[dev]

script:
  - py.test -vvv --cov=mowaki --cov-report=term-missing tests
